### PR TITLE
[WIP] Convert to TF2 + new navigation API (for melodic)

### PR DESCRIPTION
**Pull request by mintar**
**DO NOT MERGE INTO master!**

This PR updates everything to the new navigation API in melodic, which uses TF2. It does **not** work in kinetic / lunar. Therefore, a new `melodic` branch has to be created first, and this PR should only be merged into melodic.

### CODE REVIEW

**Comment by mintar** [comment]
You can test this even if you're not on melodic yet by putting the following content into a new file called "Vagrantfile" at the root of this repo and running `vagrant up`:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  $script = <<-SHELL
    export CI_ROS_DISTRO="melodic"
    export REPONAME="eband_local_planner"
    export CATKIN_WS=~/catkin_ws
    export CATKIN_WS_SRC=${CATKIN_WS}/src
    
    # set up ROS repo
    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
    wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    sudo apt-get update -qq
    sudo apt-get install -qq -y python-rosdep python-catkin-tools git build-essential cmake
    sudo rosdep init
    rosdep update
    
    # create a catkin workspace
    mkdir -p $CATKIN_WS_SRC
    cd $CATKIN_WS_SRC
    ln -s /vagrant $CATKIN_WS_SRC/$REPONAME

    # Use rosdep to install all dependencies (including ROS itself)
    rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
    
    # source setup.bash
    source /opt/ros/$CI_ROS_DISTRO/setup.bash
    cd $CATKIN_WS

    # Init catkin workspace
    catkin init
    # Enable install space
    catkin config --install
    # Build [and Install] packages
    catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
#    # Build tests
#    catkin build --limit-status-rate 0.1 --no-notify --make-args tests
#    # Run tests
#    catkin run_tests
#    catkin_test_results
#
#    # catkin_lint
#    sudo apt-get install -y python-catkin-lint
#    cd $CATKIN_WS_SRC/$REPONAME
#    catkin_lint .
  SHELL
  config.vm.provision "shell", inline: $script, privileged: false
end

```

**Comment by saikishor** [comment]
I guess this branch is good to be merged right?. I have tested the changes and it seems working. What do you say @mintar

**Comment by mintar** [comment]
Yes, I'm waiting for the maintainers to merge this too. :-(

**Comment by saikishor** [comment]
So, no more releases for `eband_local_planner`? or is there a different maintained repo?

**Comment by maxsvetlik** [comment]
A working melodic-devel branch has been merged into `master` and had a binary release for Melodic (#28). Closing this for now.

**Pull request closed without merging**
